#!/opt/homebrew/bin/bash
# Demo netcat using coprocesses.
#   before running, start a server
#   with `nc -l 50000`
#
#   requires bash 4.4 or above
#   to understand ";;&" syntax for "Check next case, too."

PORT=50000

coproc netcat { nc localhost $PORT; } # create coprocess named "netcat"
# nc is a child process
# the parent is this shell script
# netcat[0] is the file descriptor of nc's *output*
# netcat[1] is the file descriptor of nc's *input

while [[ $netcat_PID ]] &&                  # so long as the child exists
    read -r -u${netcat[0]} line; do         # and it has output
    case $line in                           # examine every line from far end
        (GOODBYE|BYE|FAREWELL)              # catch & reply to special case
            printf >&${netcat[1]} '%s\n' 'SEE YA!'
            ;;&                             # also check below
        (*)                                 # report receipt of everything
            # NB: stderr isn't passed to server, just printed here.
            printf >&2 '%s\n' "Received line: $line"
            ;;
    esac
done
